### ISSUE TITLE
Feature: 添加电费充值

### ISSUE THREAD

**Issue by Illustar0** [TorCroft/ZZU-API#3]
以下为`server/utilities/pay`中`params`的原文结构（格式化后）
```json
{
    "utilityType": "electric",
    "payCode": "06",
    "password": "XXXXX",
    "amt": "10",
    "timestamp": 233,
    "bigArea": "",
    "area": "XX",
    "building": "XX",
    "unit": "",
    "level": "XX",
    "room": "XX-XX--XX-XXX",
    "subArea": "",
    "customfield": {
    }
}
```
使用 SM2 算法 (CipherMode: C1C3C2) 对其进行加密（加密时需将其压缩），公钥由`server/auth/getEncrypt`中的`publicKey`进行 SM4 解密后得到，SM4 密钥为`773638372d392b33435f48266a655f35`

看你了.jpg

**Comment by Illustar0** [comment]
另外sign的算法其实也扣出来了....但树维完全不检验sign，很尴尬

**Comment by TorCroft** [comment]
哥们儿已经毕业了😈

**Comment by TorCroft** [comment]
> 另外sign的算法其实也扣出来了....但树维完全不检验sign，很尴尬

我记得我直接把sign删掉了

**Comment by Illustar0** [comment]
> 哥们儿已经毕业了😈

学长好.jpg
那我自己写罢 （
昨天扣这玩意扣了一晚上，电费充值系统使用sm-crypto实现的国密算法实现的不太规范....没有04头，也不认04头，搞得我懵了好半天

> > 另外sign的算法其实也扣出来了....但树维完全不检验sign，很尴尬
> 
> 我记得我直接把sign删掉了

是的，完全不校验，笑死我了，不知道放那干嘛。
这国密也逆天，放着RSA不去用跑去用国密，抽抽又象象
